sonar.projectKey=TyagiDevesh_monorepo-team-delta
sonar.projectName=TeamDelta
sonar.projectVersion=1.0.0
sonar.organization=tyagidevesh

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts,src/**/*.spec.tsx,src/**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/main.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/main.tsx,src/setupTests.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
